language: c
compiler:
 #- clang
 - gcc
script: ./configure --with-defaults && make && cd testing && ./RUNFULLTESTS
# We need libperl-dev to build with perl
# and libpython-dev to build with python
# For now we don't attempt to require specific versions.
# (I think we could use a matrix to install different
# versions of perl and python for testing)
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libperl-dev python2.7-dev
