language: c
compiler:
 - clang
 - gcc
script: ./configure --with-defaults --with-python-modules --with-security-modules=tsm --with-transports="DTLSUDP TLSTCP" --with-mib-modules="examples/example ucd-snmp/extensible" --enable-ipv6 --enable-silent-libtool && make && cd testing && ./RUNFULLTESTS
# We need libperl-dev to build with perl
# and libpython-dev to build with python
# For now we don't attempt to require specific versions.
# (I think we could use a matrix to install different
# versions of perl and python for testing)
# also need openssl for TLS support
addons:
   apt:
      packages:
         - libperl-dev
         - python2.7-dev
         - libssl-dev
#
# Try the new docker infrastructure
sudo: false
