language: c
compiler:
 - clang
 - gcc
script: ./configure --with-defaults --with-python-modules --with-security-modules=tsm --with-transports="DTLSUDP TLSTCP" --with-mib-modules="examples/example ucd-snmp/extensible" --enable-ipv6 --enable-silent-libtool $EXTRACONFIG && make && cd testing && ./RUNFULLTESTS -g all
# We need libperl-dev to build with perl
# and libpython-dev to build with python
# For now we don't attempt to require specific versions.
# (I think we could use a matrix to install different
# versions of perl and python for testing)
# also need openssl for TLS support
# The docker instance doesn't have net-tools, which
# the tests need.
addons:
   apt:
      packages:
         - libperl-dev
         - python2.7-dev
         - libssl-dev
         - net-tools
#
# Try the new docker infrastructure
sudo: false
#
# Try with and without --with-minimalist
env:
   - EXTRACONFIG=
   - EXTRACONFIG=--with-minimalist
